version: '2'
services:
  registration-service:
    build: registration-service/
    container_name: register-container
    restart: always
    hostname: localhost
    ports:
      - 8085:8085
  mongo:
    image: mongo:latest
    container_name: mongo-container
    hostname: localhost
    ports:
      - 27017:27017
