cloud:
  aws:
    credentials:
      access-key:AKIAQUIYJ2BUPLRVP2FX
      secret-key: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
    region:
      static: ap-south-1
    stack:
      auto: false

application:
  bucket:
    name: pgp-wave4-innoversity


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9090